// AUTO-GENERATED by scripts/gen-skin.mjs — DO NOT EDIT BY HAND.
// Source of truth: src/styles/tokens.css and src/styles/skin.css.
// Regenerate with `npm run gen:skin`.
/* eslint-disable */

/** A nestable CSS-in-JS style tree, as Tailwind's addBase/addComponents accept. */
export type StyleObject = { [selector: string]: string | number | StyleObject };

/** Token values as CSS-in-JS (e.g. `{ ':root': { '--ui-color-primary': '#4f46e5' } }`). */
export const tokensBase: StyleObject = {
  ":root": {
    "--ui-color-primary": "#2dd4bf",
    "--ui-color-primary-hover": "#5eead4",
    "--ui-color-primary-active": "#14b8a6",
    "--ui-color-on-primary": "#042f2a",
    "--ui-color-bg": "#0a0f1c",
    "--ui-color-surface": "#111a2e",
    "--ui-color-surface-raised": "#16213a",
    "--ui-color-surface-sunken": "#0c1424",
    "--ui-color-muted": "#1b2740",
    "--ui-color-muted-hover": "#283750",
    "--ui-color-border": "#2f3e58",
    "--ui-color-border-strong": "#475569",
    "--ui-color-text": "#e2e8f0",
    "--ui-color-text-muted": "#94a3b8",
    "--ui-color-text-subtle": "#64748b",
    "--ui-color-text-on-muted": "#cbd5e1",
    "--ui-color-danger": "#fb7185",
    "--ui-color-danger-hover": "#fda4af",
    "--ui-color-on-danger": "#4c0519",
    "--ui-color-success": "#34d399",
    "--ui-color-on-success": "#022c22",
    "--ui-color-warning": "#fbbf24",
    "--ui-color-on-warning": "#2b1d02",
    "--ui-color-info": "#60a5fa",
    "--ui-color-overlay": "rgb(2 6 23 / 0.72)",
    "--ui-border-style": "dashed",
    "--ui-border-width": "1.5px",
    "--ui-grid-dot": "rgb(148 163 184 / 0.16)",
    "--ui-grid-size": "22px",
    "--ui-canvas-grid": "radial-gradient(\n    var(--ui-grid-dot) 1.2px,\n    transparent 1.2px\n  )",
    "--ui-color-selection": "rgb(45 212 191 / 0.14)",
    "--ui-color-selection-line": "var(--ui-color-primary)",
    "--ui-color-planned": "#64748b",
    "--ui-font-family": "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto,\n    sans-serif",
    "--ui-font-mono": "ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, Consolas,\n    monospace",
    "--ui-font-weight-normal": "400",
    "--ui-font-weight-medium": "500",
    "--ui-font-weight-semibold": "600",
    "--ui-font-size-xs": "0.75rem",
    "--ui-font-size-sm": "0.875rem",
    "--ui-font-size-md": "1rem",
    "--ui-font-size-lg": "1.125rem",
    "--ui-font-size-xl": "1.375rem",
    "--ui-line-height": "1.5",
    "--ui-space-1": "0.25rem",
    "--ui-space-2": "0.5rem",
    "--ui-space-3": "0.75rem",
    "--ui-space-4": "1rem",
    "--ui-space-5": "1.5rem",
    "--ui-space-6": "2rem",
    "--ui-radius-sm": "3px",
    "--ui-radius-md": "5px",
    "--ui-radius-lg": "8px",
    "--ui-radius-xl": "12px",
    "--ui-radius-pill": "9999px",
    "--ui-control-height-sm": "1.75rem",
    "--ui-control-height-md": "2.25rem",
    "--ui-control-height-lg": "2.75rem",
    "--ui-control-padding-x": "var(--ui-space-3)",
    "--ui-shadow-sm": "0 1px 2px rgb(0 0 0 / 0.4)",
    "--ui-shadow-md": "0 6px 18px rgb(0 0 0 / 0.5)",
    "--ui-shadow-lg": "0 22px 50px rgb(0 0 0 / 0.6)",
    "--ui-focus-ring-color": "rgb(45 212 191 / 0.5)",
    "--ui-focus-ring": "0 0 0 3px var(--ui-focus-ring-color)",
    "--ui-transition": "150ms ease",
    "--ui-z-popover": "50",
    "--ui-z-overlay": "60",
    "--ui-z-modal": "70",
    "--ui-z-toast": "80",
    "--ui-shell-header-height": "3.5rem",
    "--ui-shell-sidebar-width": "15rem"
  }
};

/** Default skin as CSS-in-JS, keyed by `[data-ui-*]` selectors and `@keyframes`. */
export const skinComponents: StyleObject = {
  "@keyframes ui-spin": {
    "to": {
      "transform": "rotate(360deg)"
    }
  },
  "@keyframes ui-pulse": {
    "50%": {
      "opacity": 0.55
    }
  },
  "@keyframes ui-fade-in": {
    "from": {
      "opacity": 0
    }
  },
  "@keyframes ui-zoom-in": {
    "from": {
      "opacity": 0,
      "transform": "translate(-50%, -50%) scale(0.96)"
    }
  },
  "[data-ui-planned]": {
    "position": "relative",
    "outline": "var(--ui-border-width) dotted var(--ui-color-planned)",
    "outlineOffset": "4px",
    "borderRadius": "var(--ui-radius-sm)",
    "opacity": 0.85
  },
  "[data-ui-planned]::after": {
    "content": "\"planned\"",
    "position": "absolute",
    "top": "0",
    "right": "var(--ui-space-2)",
    "transform": "translateY(-50%)",
    "padding": "0 var(--ui-space-1)",
    "background": "var(--ui-color-bg)",
    "color": "var(--ui-color-planned)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "0.625rem",
    "fontWeight": "var(--ui-font-weight-medium)",
    "letterSpacing": "0.08em",
    "textTransform": "uppercase"
  },
  "[data-ui-button]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "var(--ui-space-2)",
    "height": "var(--ui-control-height-md)",
    "paddingInline": "var(--ui-space-4)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-surface)",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "lineHeight": 1,
    "whiteSpace": "nowrap",
    "cursor": "pointer",
    "userSelect": "none",
    "textDecoration": "none",
    "transition": "background-color var(--ui-transition),\n    border-color var(--ui-transition),\n    color var(--ui-transition),\n    box-shadow var(--ui-transition)"
  },
  "[data-ui-button]:hover": {
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-button]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-button]:disabled,\n[data-ui-button][data-disabled],\n[data-ui-button][aria-disabled=\"true\"]": {
    "opacity": 0.5,
    "pointerEvents": "none"
  },
  "[data-ui-button][data-variant=\"primary\"]": {
    "background": "var(--ui-color-primary)",
    "borderColor": "var(--ui-color-primary)",
    "color": "var(--ui-color-on-primary)"
  },
  "[data-ui-button][data-variant=\"primary\"]:hover": {
    "background": "var(--ui-color-primary-hover)",
    "borderColor": "var(--ui-color-primary-hover)"
  },
  "[data-ui-button][data-variant=\"primary\"]:active": {
    "background": "var(--ui-color-primary-active)"
  },
  "[data-ui-button][data-variant=\"secondary\"]": {
    "background": "var(--ui-color-muted)",
    "borderColor": "var(--ui-color-muted)",
    "color": "var(--ui-color-text-on-muted)"
  },
  "[data-ui-button][data-variant=\"secondary\"]:hover": {
    "background": "var(--ui-color-muted-hover)",
    "borderColor": "var(--ui-color-muted-hover)"
  },
  "[data-ui-button][data-variant=\"outline\"]": {
    "background": "transparent"
  },
  "[data-ui-button][data-variant=\"outline\"]:hover": {
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-button][data-variant=\"ghost\"]": {
    "background": "transparent",
    "borderColor": "transparent"
  },
  "[data-ui-button][data-variant=\"ghost\"]:hover": {
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-button][data-variant=\"danger\"]": {
    "background": "var(--ui-color-danger)",
    "borderColor": "var(--ui-color-danger)",
    "color": "var(--ui-color-on-danger)"
  },
  "[data-ui-button][data-variant=\"danger\"]:hover": {
    "background": "var(--ui-color-danger-hover)",
    "borderColor": "var(--ui-color-danger-hover)"
  },
  "[data-ui-button][data-size=\"sm\"]": {
    "height": "var(--ui-control-height-sm)",
    "paddingInline": "var(--ui-space-3)",
    "fontSize": "var(--ui-font-size-xs)"
  },
  "[data-ui-button][data-size=\"lg\"]": {
    "height": "var(--ui-control-height-lg)",
    "paddingInline": "var(--ui-space-5)",
    "fontSize": "var(--ui-font-size-md)"
  },
  "[data-ui-tag]": {
    "display": "inline-flex",
    "alignItems": "center",
    "padding": "0.1em var(--ui-space-2)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "borderRadius": "var(--ui-radius-sm)",
    "background": "var(--ui-color-surface-sunken)",
    "color": "var(--ui-color-text-muted)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "0.6875rem",
    "lineHeight": 1.4,
    "whiteSpace": "nowrap"
  },
  "[data-ui-tag][data-variant=\"primary\"]": {
    "background": "rgb(45 212 191 / 0.08)",
    "borderColor": "rgb(45 212 191 / 0.3)",
    "color": "var(--ui-color-primary)"
  },
  "[data-ui-badge]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-1)",
    "padding": "0.1em var(--ui-space-2)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-sm)",
    "background": "transparent",
    "color": "var(--ui-color-text-muted)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-xs)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "letterSpacing": "0.04em",
    "textTransform": "uppercase",
    "lineHeight": 1.4,
    "whiteSpace": "nowrap"
  },
  "[data-ui-badge][data-variant=\"primary\"]": {
    "background": "var(--ui-color-primary)",
    "borderColor": "var(--ui-color-primary)",
    "color": "var(--ui-color-on-primary)"
  },
  "[data-ui-badge][data-variant=\"success\"]": {
    "background": "var(--ui-color-success)",
    "borderColor": "var(--ui-color-success)",
    "color": "var(--ui-color-on-success)"
  },
  "[data-ui-badge][data-variant=\"warning\"]": {
    "background": "var(--ui-color-warning)",
    "borderColor": "var(--ui-color-warning)",
    "color": "var(--ui-color-on-warning)"
  },
  "[data-ui-badge][data-variant=\"danger\"]": {
    "background": "var(--ui-color-danger)",
    "borderColor": "var(--ui-color-danger)",
    "color": "var(--ui-color-on-danger)"
  },
  "[data-ui-input],\n[data-ui-textarea],\n[data-ui-select-trigger]": {
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "color": "var(--ui-color-text)",
    "background": "var(--ui-color-surface)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "transition": "border-color var(--ui-transition),\n    box-shadow var(--ui-transition)"
  },
  "[data-ui-input],\n[data-ui-select-trigger]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "height": "var(--ui-control-height-md)",
    "paddingInline": "var(--ui-space-3)",
    "width": "100%"
  },
  "[data-ui-textarea]": {
    "display": "block",
    "width": "100%",
    "minHeight": "calc(var(--ui-control-height-md) * 2)",
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "lineHeight": "var(--ui-line-height)",
    "resize": "vertical"
  },
  "[data-ui-input]::placeholder,\n[data-ui-textarea]::placeholder": {
    "color": "var(--ui-color-text-subtle)"
  },
  "[data-ui-input]:focus-visible,\n[data-ui-textarea]:focus-visible,\n[data-ui-select-trigger]:focus-visible": {
    "outline": "none",
    "borderStyle": "solid",
    "borderColor": "var(--ui-color-primary)",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-input]:disabled,\n[data-ui-textarea]:disabled,\n[data-ui-select-trigger][data-disabled]": {
    "opacity": 0.5,
    "cursor": "not-allowed",
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-input][data-invalid],\n[data-ui-textarea][aria-invalid=\"true\"]": {
    "borderColor": "var(--ui-color-danger)"
  },
  "[data-ui-input][data-invalid]:focus-visible": {
    "boxShadow": "0 0 0 3px rgb(251 113 133 / 0.4)"
  },
  "[data-ui-label]": {
    "display": "inline-block",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-checkbox]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "width": "1.15rem",
    "height": "1.15rem",
    "padding": "0",
    "border": "var(--ui-border-width) solid var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-sm)",
    "background": "var(--ui-color-surface)",
    "color": "var(--ui-color-on-primary)",
    "cursor": "pointer",
    "transition": "background-color var(--ui-transition),\n    border-color var(--ui-transition)"
  },
  "[data-ui-checkbox][data-state=\"checked\"],\n[data-ui-checkbox][data-state=\"indeterminate\"]": {
    "background": "var(--ui-color-primary)",
    "borderColor": "var(--ui-color-primary)"
  },
  "[data-ui-checkbox]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-checkbox]:disabled": {
    "opacity": 0.5,
    "cursor": "not-allowed"
  },
  "[data-ui-checkbox-indicator]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "width": "100%",
    "height": "100%",
    "fontSize": "0.8rem",
    "lineHeight": 1
  },
  "[data-ui-radio-group]": {
    "display": "grid",
    "gap": "var(--ui-space-2)"
  },
  "[data-ui-radio-group-item]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "width": "1.15rem",
    "height": "1.15rem",
    "padding": "0",
    "border": "var(--ui-border-width) solid var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-surface)",
    "cursor": "pointer",
    "transition": "border-color var(--ui-transition)"
  },
  "[data-ui-radio-group-item][data-state=\"checked\"]": {
    "borderColor": "var(--ui-color-primary)"
  },
  "[data-ui-radio-group-item]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-radio-group-item]:disabled": {
    "opacity": 0.5,
    "cursor": "not-allowed"
  },
  "[data-ui-radio-group-indicator]": {
    "display": "inline-flex",
    "width": "100%",
    "height": "100%",
    "alignItems": "center",
    "justifyContent": "center"
  },
  "[data-ui-radio-group-indicator]::after": {
    "content": "\"\"",
    "width": "0.55rem",
    "height": "0.55rem",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-primary)"
  },
  "[data-ui-switch]": {
    "display": "inline-flex",
    "alignItems": "center",
    "width": "2.5rem",
    "height": "1.4rem",
    "padding": "2px",
    "border": "var(--ui-border-width) solid var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-muted)",
    "cursor": "pointer",
    "transition": "background-color var(--ui-transition),\n    border-color var(--ui-transition)"
  },
  "[data-ui-switch][data-state=\"checked\"]": {
    "background": "var(--ui-color-primary)",
    "borderColor": "var(--ui-color-primary)"
  },
  "[data-ui-switch]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-switch]:disabled": {
    "opacity": 0.5,
    "cursor": "not-allowed"
  },
  "[data-ui-switch-thumb]": {
    "display": "block",
    "width": "1rem",
    "height": "1rem",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-surface)",
    "boxShadow": "var(--ui-shadow-sm)",
    "transition": "transform var(--ui-transition)",
    "transform": "translateX(0)"
  },
  "[data-ui-switch-thumb][data-state=\"checked\"]": {
    "transform": "translateX(1.1rem)"
  },
  "[data-ui-slider]": {
    "position": "relative",
    "display": "flex",
    "alignItems": "center",
    "userSelect": "none",
    "touchAction": "none"
  },
  "[data-ui-slider][data-orientation=\"horizontal\"]": {
    "width": "100%",
    "height": "1.25rem"
  },
  "[data-ui-slider][data-orientation=\"vertical\"]": {
    "flexDirection": "column",
    "width": "1.25rem",
    "height": "12rem"
  },
  "[data-ui-slider-track]": {
    "position": "relative",
    "flexGrow": 1,
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-muted-hover)"
  },
  "[data-ui-slider][data-orientation=\"horizontal\"] [data-ui-slider-track]": {
    "height": "0.35rem"
  },
  "[data-ui-slider][data-orientation=\"vertical\"] [data-ui-slider-track]": {
    "width": "0.35rem"
  },
  "[data-ui-slider-range]": {
    "position": "absolute",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-primary)"
  },
  "[data-ui-slider][data-orientation=\"horizontal\"] [data-ui-slider-range]": {
    "height": "100%"
  },
  "[data-ui-slider][data-orientation=\"vertical\"] [data-ui-slider-range]": {
    "width": "100%"
  },
  "[data-ui-slider-thumb]": {
    "display": "block",
    "width": "1.1rem",
    "height": "1.1rem",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-surface)",
    "border": "2px solid var(--ui-color-primary)",
    "boxShadow": "var(--ui-shadow-sm)"
  },
  "[data-ui-slider-thumb]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-progress]": {
    "position": "relative",
    "overflow": "hidden",
    "width": "100%",
    "height": "0.6rem",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-progress-indicator]": {
    "width": "100%",
    "height": "100%",
    "background": "var(--ui-color-primary)",
    "transition": "transform var(--ui-transition)"
  },
  "[data-ui-avatar]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "verticalAlign": "middle",
    "overflow": "hidden",
    "width": "2.5rem",
    "height": "2.5rem",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-pill)",
    "background": "var(--ui-color-muted)",
    "userSelect": "none"
  },
  "[data-ui-avatar-image]": {
    "width": "100%",
    "height": "100%",
    "objectFit": "cover"
  },
  "[data-ui-avatar-fallback]": {
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "width": "100%",
    "height": "100%",
    "color": "var(--ui-color-text-on-muted)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)"
  },
  "[data-ui-card]": {
    "display": "flex",
    "flexDirection": "column",
    "background": "var(--ui-color-surface)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "borderRadius": "var(--ui-radius-lg)",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)"
  },
  "[data-ui-card-header]": {
    "display": "flex",
    "flexDirection": "column",
    "gap": "var(--ui-space-1)",
    "padding": "var(--ui-space-5)",
    "paddingBottom": "var(--ui-space-3)"
  },
  "[data-ui-card-title]": {
    "margin": "0",
    "fontSize": "var(--ui-font-size-lg)",
    "fontWeight": "var(--ui-font-weight-semibold)"
  },
  "[data-ui-card-description]": {
    "margin": "0",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-card-body]": {
    "padding": "var(--ui-space-5)",
    "paddingBlock": "var(--ui-space-3)"
  },
  "[data-ui-card-footer]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "padding": "var(--ui-space-5)",
    "paddingTop": "var(--ui-space-3)"
  },
  "[data-ui-table]": {
    "width": "100%",
    "borderCollapse": "collapse",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-table-header-cell]": {
    "textAlign": "left",
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "background": "var(--ui-color-surface-sunken)",
    "borderBottom": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "fontSize": "var(--ui-font-size-xs)",
    "fontWeight": "var(--ui-font-weight-semibold)",
    "textTransform": "uppercase",
    "letterSpacing": "0.04em",
    "color": "var(--ui-color-text-subtle)",
    "whiteSpace": "nowrap"
  },
  "[data-ui-table-cell]": {
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "borderBottom": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "whiteSpace": "nowrap"
  },
  "[data-ui-table-body] [data-ui-table-row]:last-child [data-ui-table-cell]": {
    "borderBottom": "none"
  },
  "[data-ui-table-body] [data-ui-table-row]:hover": {
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-separator]": {
    "flexShrink": 0,
    "border": "0",
    "borderColor": "var(--ui-color-border)"
  },
  "[data-ui-separator][data-orientation=\"horizontal\"]": {
    "width": "100%",
    "borderTop": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "marginBlock": "var(--ui-space-3)"
  },
  "[data-ui-separator][data-orientation=\"vertical\"]": {
    "alignSelf": "stretch",
    "borderLeft": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "marginInline": "var(--ui-space-3)"
  },
  "[data-ui-skeleton]": {
    "minHeight": "1em",
    "border": "var(--ui-border-width) dashed var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "repeating-linear-gradient(\n    45deg,\n    var(--ui-color-muted),\n    var(--ui-color-muted) 6px,\n    var(--ui-color-surface) 6px,\n    var(--ui-color-surface) 12px\n  )",
    "animation": "ui-pulse 1.6s ease-in-out infinite"
  },
  "[data-ui-spinner]": {
    "display": "inline-block",
    "width": "1.25rem",
    "height": "1.25rem",
    "border": "2px solid var(--ui-color-muted-hover)",
    "borderTopColor": "var(--ui-color-primary)",
    "borderRadius": "var(--ui-radius-pill)",
    "animation": "ui-spin 0.6s linear infinite",
    "verticalAlign": "middle"
  },
  "[data-ui-spinner]:has(> [aria-hidden=\"true\"])": {
    "border": "none",
    "animation": "none",
    "width": "auto",
    "height": "auto"
  },
  "[data-ui-popover-content],\n[data-ui-hover-card-content],\n[data-ui-dropdown-menu-content],\n[data-ui-dropdown-menu-sub-content],\n[data-ui-select-content]": {
    "background": "var(--ui-color-surface)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "boxShadow": "var(--ui-shadow-md)",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "zIndex": "var(--ui-z-popover)",
    "animation": "ui-fade-in var(--ui-transition)"
  },
  "[data-ui-popover-content],\n[data-ui-hover-card-content]": {
    "padding": "var(--ui-space-4)",
    "maxWidth": "20rem"
  },
  "[data-ui-dropdown-menu-content],\n[data-ui-dropdown-menu-sub-content],\n[data-ui-select-content]": {
    "padding": "var(--ui-space-1)",
    "minWidth": "9rem"
  },
  "[data-ui-popover-arrow],\n[data-ui-hover-card-arrow],\n[data-ui-tooltip-arrow]": {
    "fill": "var(--ui-color-surface)"
  },
  "[data-ui-tooltip-content]": {
    "background": "var(--ui-color-text)",
    "color": "var(--ui-color-surface)",
    "padding": "var(--ui-space-1) var(--ui-space-2)",
    "borderRadius": "var(--ui-radius-sm)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-xs)",
    "zIndex": "var(--ui-z-popover)",
    "animation": "ui-fade-in var(--ui-transition)"
  },
  "[data-ui-tooltip-content] [data-ui-tooltip-arrow]": {
    "fill": "var(--ui-color-text)"
  },
  "[data-ui-dropdown-menu-item],\n[data-ui-dropdown-menu-checkbox-item],\n[data-ui-dropdown-menu-radio-item],\n[data-ui-dropdown-menu-sub-trigger],\n[data-ui-select-item]": {
    "position": "relative",
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "borderRadius": "var(--ui-radius-sm)",
    "fontSize": "var(--ui-font-size-sm)",
    "cursor": "pointer",
    "userSelect": "none",
    "outline": "none"
  },
  "[data-ui-dropdown-menu-item][data-highlighted],\n[data-ui-dropdown-menu-checkbox-item][data-highlighted],\n[data-ui-dropdown-menu-radio-item][data-highlighted],\n[data-ui-dropdown-menu-sub-trigger][data-highlighted],\n[data-ui-select-item][data-highlighted]": {
    "background": "var(--ui-color-selection)",
    "boxShadow": "inset 2px 0 0 var(--ui-color-selection-line)"
  },
  "[data-ui-select-item][data-state=\"checked\"]": {
    "color": "var(--ui-color-primary)"
  },
  "[data-ui-dropdown-menu-item][data-disabled],\n[data-ui-select-item][data-disabled]": {
    "opacity": 0.5,
    "pointerEvents": "none"
  },
  "[data-ui-dropdown-menu-label],\n[data-ui-select-label]": {
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "color": "var(--ui-color-text-muted)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-xs)",
    "fontWeight": "var(--ui-font-weight-semibold)",
    "textTransform": "uppercase",
    "letterSpacing": "0.06em"
  },
  "[data-ui-dropdown-menu-separator],\n[data-ui-select-separator]": {
    "height": "0",
    "margin": "var(--ui-space-1) calc(-1 * var(--ui-space-1))",
    "borderTop": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)"
  },
  "[data-ui-select-item-indicator],\n[data-ui-dropdown-menu-item-indicator]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "color": "var(--ui-color-primary)"
  },
  "[data-ui-select-trigger]": {
    "justifyContent": "space-between",
    "cursor": "pointer"
  },
  "[data-ui-select-icon]": {
    "display": "inline-flex",
    "color": "var(--ui-color-text-muted)"
  },
  "[data-ui-dialog-overlay],\n[data-ui-alert-dialog-overlay]": {
    "position": "fixed",
    "inset": "0",
    "background": "var(--ui-color-overlay)",
    "zIndex": "var(--ui-z-overlay)",
    "animation": "ui-fade-in var(--ui-transition)"
  },
  "[data-ui-dialog-content],\n[data-ui-alert-dialog-content]": {
    "position": "fixed",
    "top": "50%",
    "left": "50%",
    "transform": "translate(-50%, -50%)",
    "width": "92vw",
    "maxWidth": "32rem",
    "maxHeight": "85vh",
    "overflow": "auto",
    "padding": "var(--ui-space-5)",
    "background": "var(--ui-color-surface)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-lg)",
    "boxShadow": "var(--ui-shadow-lg)",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)",
    "zIndex": "var(--ui-z-modal)",
    "animation": "ui-zoom-in var(--ui-transition)"
  },
  "[data-ui-dialog-title],\n[data-ui-alert-dialog-title]": {
    "margin": "0 0 var(--ui-space-2)",
    "fontSize": "var(--ui-font-size-lg)",
    "fontWeight": "var(--ui-font-weight-semibold)"
  },
  "[data-ui-dialog-description],\n[data-ui-alert-dialog-description]": {
    "margin": "0 0 var(--ui-space-4)",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-tabs]": {
    "fontFamily": "var(--ui-font-family)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-tabs-list]": {
    "display": "flex",
    "gap": "var(--ui-space-1)",
    "borderBottom": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)"
  },
  "[data-ui-tabs-trigger]": {
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "border": "none",
    "background": "none",
    "color": "var(--ui-color-text-muted)",
    "font": "inherit",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "cursor": "pointer",
    "borderBottom": "2px solid transparent",
    "marginBottom": "calc(-1 * var(--ui-border-width))",
    "transition": "color var(--ui-transition),\n    background-color var(--ui-transition),\n    border-color var(--ui-transition)"
  },
  "[data-ui-tabs-trigger]:hover": {
    "color": "var(--ui-color-text)"
  },
  "[data-ui-tabs-trigger][data-state=\"active\"]": {
    "color": "var(--ui-color-primary)",
    "background": "var(--ui-color-selection)",
    "borderBottomColor": "var(--ui-color-selection-line)"
  },
  "[data-ui-tabs-trigger]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)",
    "borderRadius": "var(--ui-radius-sm)"
  },
  "[data-ui-tabs-content]": {
    "paddingTop": "var(--ui-space-4)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-accordion],\n[data-ui-collapsible]": {
    "fontFamily": "var(--ui-font-family)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-accordion-item]": {
    "borderBottom": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)"
  },
  "[data-ui-accordion-header]": {
    "margin": "0"
  },
  "[data-ui-accordion-trigger],\n[data-ui-collapsible-trigger]": {
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "space-between",
    "width": "100%",
    "padding": "var(--ui-space-3) 0",
    "border": "none",
    "background": "none",
    "color": "inherit",
    "font": "inherit",
    "fontWeight": "var(--ui-font-weight-medium)",
    "textAlign": "left",
    "cursor": "pointer"
  },
  "[data-ui-accordion-trigger]:focus-visible,\n[data-ui-collapsible-trigger]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)",
    "borderRadius": "var(--ui-radius-sm)"
  },
  "[data-ui-accordion-content],\n[data-ui-collapsible-content]": {
    "paddingBottom": "var(--ui-space-3)",
    "fontSize": "var(--ui-font-size-sm)",
    "color": "var(--ui-color-text-muted)"
  },
  "[data-ui-toast-viewport]": {
    "position": "fixed",
    "bottom": "0",
    "right": "0",
    "display": "flex",
    "flexDirection": "column",
    "gap": "var(--ui-space-2)",
    "width": "24rem",
    "maxWidth": "100vw",
    "padding": "var(--ui-space-4)",
    "margin": "0",
    "listStyle": "none",
    "zIndex": "var(--ui-z-toast)"
  },
  "[data-ui-toast]": {
    "display": "grid",
    "gridTemplateColumns": "1fr auto",
    "gap": "var(--ui-space-1) var(--ui-space-3)",
    "alignItems": "center",
    "padding": "var(--ui-space-3) var(--ui-space-4)",
    "background": "var(--ui-color-surface)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "boxShadow": "var(--ui-shadow-md)",
    "fontFamily": "var(--ui-font-family)",
    "animation": "ui-fade-in var(--ui-transition)"
  },
  "[data-ui-toast-title]": {
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-semibold)"
  },
  "[data-ui-toast-description]": {
    "gridColumn": "1",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-toast-action],\n[data-ui-toast-close]": {
    "gridColumn": "2",
    "gridRow": "1"
  },
  "[data-ui-application]": {
    "display": "flex",
    "flexDirection": "column",
    "minHeight": "100vh",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-md)",
    "lineHeight": "var(--ui-line-height)",
    "backgroundColor": "var(--ui-color-bg)",
    "backgroundImage": "var(--ui-canvas-grid)",
    "backgroundSize": "var(--ui-grid-size) var(--ui-grid-size)",
    "backgroundPosition": "-1px -1px"
  },
  "[data-ui-header]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-4)",
    "height": "var(--ui-shell-header-height)",
    "paddingInline": "var(--ui-space-4)",
    "background": "var(--ui-color-surface)",
    "borderBottom": "var(--ui-border-width) var(--ui-border-style)\n    var(--ui-color-border)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-footer]": {
    "padding": "var(--ui-space-4) var(--ui-space-5)",
    "background": "var(--ui-color-surface)",
    "borderTop": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-sidebar]": {
    "flexShrink": 0,
    "width": "var(--ui-shell-sidebar-width)",
    "padding": "var(--ui-space-4)",
    "background": "var(--ui-color-surface)",
    "borderRight": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)"
  },
  "[data-ui-content]": {
    "padding": "var(--ui-space-5)"
  },
  "[data-ui-page]": {
    "display": "block",
    "padding": "var(--ui-space-5)"
  },
  "[data-ui-application-module]": {
    "display": "block"
  },
  "[data-ui-container]": {
    "width": "100%",
    "maxWidth": "64rem",
    "marginInline": "auto",
    "paddingInline": "var(--ui-space-4)"
  },
  "[data-ui-inline]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)"
  },
  "[data-ui-inline] > [data-ui-input],\n[data-ui-inline] > [data-ui-select-trigger]": {
    "flex": "1 1 auto",
    "minWidth": "0"
  },
  "[data-ui-header-brand]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "fontWeight": "var(--ui-font-weight-semibold)",
    "color": "var(--ui-color-text)",
    "textDecoration": "none",
    "whiteSpace": "nowrap"
  },
  "[data-ui-header-nav]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-1)"
  },
  "[data-ui-header-nav] a": {
    "display": "inline-flex",
    "alignItems": "center",
    "padding": "var(--ui-space-1) var(--ui-space-3)",
    "borderRadius": "var(--ui-radius-md)",
    "color": "var(--ui-color-text-muted)",
    "textDecoration": "none",
    "fontSize": "var(--ui-font-size-sm)",
    "transition": "background-color var(--ui-transition),\n    color var(--ui-transition)"
  },
  "[data-ui-header-nav] a:hover": {
    "background": "var(--ui-color-muted)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-header-nav] a[aria-current]": {
    "color": "var(--ui-color-text)",
    "boxShadow": "inset 0 -2px 0 0 var(--ui-color-selection-line)"
  },
  "[data-ui-header-search]": {
    "display": "flex",
    "alignItems": "center",
    "flex": "1 1 auto",
    "minWidth": "0",
    "maxWidth": "22rem"
  },
  "[data-ui-header-search] > *": {
    "width": "100%"
  },
  "[data-ui-header-spacer]": {
    "flex": "1 1 auto"
  },
  "[data-ui-header-actions]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "marginInlineStart": "auto"
  },
  "[data-ui-app-shell]": {
    "display": "flex",
    "flexDirection": "column"
  },
  "[data-ui-app-shell-body]": {
    "display": "flex",
    "alignItems": "stretch",
    "flex": "1 1 auto",
    "minHeight": "0"
  },
  "[data-ui-app-shell-body] > [data-ui-page]": {
    "flex": "1 1 auto",
    "minWidth": "0"
  },
  "[data-ui-navrail]": {
    "display": "flex",
    "flexDirection": "column",
    "gap": "var(--ui-space-1)"
  },
  "[data-ui-navrail-section]": {
    "display": "flex",
    "flexDirection": "column",
    "gap": "var(--ui-space-1)",
    "paddingBlock": "var(--ui-space-2)"
  },
  "[data-ui-navrail-section] + [data-ui-navrail-section]": {
    "borderTop": "var(--ui-border-width) var(--ui-border-style)\n    var(--ui-color-border)"
  },
  "[data-ui-navrail-label]": {
    "paddingInline": "var(--ui-space-3)",
    "marginBottom": "var(--ui-space-1)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-xs)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "textTransform": "uppercase",
    "letterSpacing": "0.06em",
    "color": "var(--ui-color-text-subtle)"
  },
  "[data-ui-navrail-item]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "borderRadius": "var(--ui-radius-md)",
    "color": "var(--ui-color-text-muted)",
    "textDecoration": "none",
    "fontSize": "var(--ui-font-size-sm)",
    "transition": "background-color var(--ui-transition),\n    color var(--ui-transition)"
  },
  "[data-ui-navrail-item]:hover": {
    "background": "var(--ui-color-muted)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-navrail-item][aria-current=\"page\"]": {
    "background": "var(--ui-color-selection)",
    "color": "var(--ui-color-text)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "boxShadow": "inset 2px 0 0 0 var(--ui-color-selection-line)"
  },
  "[data-ui-navrail-item]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-page-header]": {
    "display": "flex",
    "flexDirection": "column",
    "gap": "var(--ui-space-3)",
    "paddingBottom": "var(--ui-space-4)",
    "marginBottom": "var(--ui-space-5)",
    "borderBottom": "var(--ui-border-width) var(--ui-border-style)\n    var(--ui-color-border)"
  },
  "[data-ui-page-header-breadcrumb]": {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-page-header-breadcrumb-item]": {
    "color": "var(--ui-color-text-muted)",
    "textDecoration": "none"
  },
  "[data-ui-page-header-breadcrumb-item]:hover": {
    "color": "var(--ui-color-primary)",
    "textDecoration": "underline"
  },
  "[data-ui-page-header-breadcrumb-item][aria-current=\"page\"]": {
    "color": "var(--ui-color-text)"
  },
  "[data-ui-page-header-breadcrumb-item]\n  + [data-ui-page-header-breadcrumb-item]::before": {
    "content": "\"/\"",
    "marginInlineEnd": "var(--ui-space-2)",
    "color": "var(--ui-color-text-subtle)"
  },
  "[data-ui-page-header-heading]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-3)"
  },
  "[data-ui-page-header-title]": {
    "margin": "0",
    "fontSize": "var(--ui-font-size-xl)",
    "fontWeight": "var(--ui-font-weight-semibold)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-page-header-actions]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "marginInlineStart": "auto"
  },
  "[data-ui-page-header-description]": {
    "margin": "0",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-list]": {
    "listStyle": "none",
    "margin": "0",
    "padding": "0",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-surface)",
    "overflow": "hidden"
  },
  "[data-ui-list-row]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-3)",
    "padding": "var(--ui-space-2) var(--ui-space-4)",
    "color": "var(--ui-color-text)",
    "textDecoration": "none",
    "transition": "background-color var(--ui-transition)"
  },
  "[data-ui-list-row] + [data-ui-list-row]": {
    "borderTop": "var(--ui-border-width) var(--ui-border-style)\n    var(--ui-color-border)"
  },
  "a[data-ui-list-row]:hover,\n[data-ui-list-row][role=\"button\"]:hover": {
    "background": "var(--ui-color-surface-raised)"
  },
  "[data-ui-list-row]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-list-leading]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "flexShrink": 0,
    "color": "var(--ui-color-text-muted)"
  },
  "[data-ui-list-main]": {
    "display": "flex",
    "flexDirection": "column",
    "gap": "2px",
    "flex": "1 1 auto",
    "minWidth": "0"
  },
  "[data-ui-list-title]": {
    "fontWeight": "var(--ui-font-weight-semibold)",
    "fontSize": "var(--ui-font-size-sm)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-list-title] a": {
    "color": "var(--ui-color-primary)",
    "textDecoration": "none"
  },
  "[data-ui-list-title] a:hover": {
    "textDecoration": "underline"
  },
  "[data-ui-list-description]": {
    "fontSize": "var(--ui-font-size-xs)",
    "color": "var(--ui-color-text-muted)",
    "whiteSpace": "nowrap",
    "overflow": "hidden",
    "textOverflow": "ellipsis"
  },
  "[data-ui-list-trailing]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "flexShrink": 0,
    "marginInlineStart": "auto",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-xs)"
  },
  "[data-ui-empty-state]": {
    "display": "flex",
    "flexDirection": "column",
    "alignItems": "center",
    "textAlign": "center",
    "gap": "var(--ui-space-3)",
    "padding": "var(--ui-space-6) var(--ui-space-5)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-surface)",
    "color": "var(--ui-color-text-muted)"
  },
  "[data-ui-empty-state-icon]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "fontSize": "var(--ui-font-size-xl)",
    "color": "var(--ui-color-text-subtle)"
  },
  "[data-ui-empty-state-title]": {
    "margin": "0",
    "fontSize": "var(--ui-font-size-lg)",
    "fontWeight": "var(--ui-font-weight-semibold)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-empty-state-description]": {
    "margin": "0",
    "maxWidth": "28rem",
    "fontSize": "var(--ui-font-size-sm)",
    "color": "var(--ui-color-text-muted)"
  },
  "[data-ui-empty-state-actions]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "marginTop": "var(--ui-space-2)"
  },
  "[data-ui-command-overlay]": {
    "position": "fixed",
    "inset": "0",
    "zIndex": "var(--ui-z-overlay)",
    "background": "var(--ui-color-overlay)",
    "animation": "ui-fade-in var(--ui-transition)"
  },
  "[data-ui-command-dialog]": {
    "position": "fixed",
    "top": "15vh",
    "left": "50%",
    "transform": "translateX(-50%)",
    "zIndex": "var(--ui-z-modal)",
    "width": "min(40rem, calc(100vw - 2 * var(--ui-space-4)))",
    "background": "var(--ui-color-surface-raised)",
    "border": "var(--ui-border-width) var(--ui-border-style)\n    var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-lg)",
    "boxShadow": "var(--ui-shadow-lg)",
    "overflow": "hidden",
    "animation": "ui-fade-in var(--ui-transition)"
  },
  "[data-ui-command]": {
    "display": "flex",
    "flexDirection": "column",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)"
  },
  "[data-ui-command-input]": {
    "width": "100%",
    "boxSizing": "border-box",
    "padding": "var(--ui-space-4)",
    "border": "none",
    "borderBottom": "var(--ui-border-width) var(--ui-border-style)\n    var(--ui-color-border)",
    "background": "transparent",
    "color": "var(--ui-color-text)",
    "fontFamily": "inherit",
    "fontSize": "var(--ui-font-size-md)",
    "outline": "none"
  },
  "[data-ui-command-input]::placeholder": {
    "color": "var(--ui-color-text-subtle)"
  },
  "[data-ui-command-list]": {
    "maxHeight": "22rem",
    "overflowY": "auto",
    "padding": "var(--ui-space-2)"
  },
  "[data-ui-command-group] + [data-ui-command-group]": {
    "marginTop": "var(--ui-space-2)"
  },
  "[data-ui-command-group-heading]": {
    "padding": "var(--ui-space-2) var(--ui-space-2) var(--ui-space-1)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-xs)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "textTransform": "uppercase",
    "letterSpacing": "0.06em",
    "color": "var(--ui-color-text-subtle)"
  },
  "[data-ui-command-item]": {
    "display": "flex",
    "alignItems": "center",
    "gap": "var(--ui-space-3)",
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "borderRadius": "var(--ui-radius-md)",
    "color": "var(--ui-color-text)",
    "fontSize": "var(--ui-font-size-sm)",
    "cursor": "pointer",
    "userSelect": "none"
  },
  "[data-ui-command-item][data-active]": {
    "background": "var(--ui-color-selection)",
    "boxShadow": "inset 2px 0 0 0 var(--ui-color-selection-line)"
  },
  "[data-ui-command-item][data-disabled]": {
    "color": "var(--ui-color-text-subtle)",
    "cursor": "default"
  },
  "[data-ui-command-empty]": {
    "padding": "var(--ui-space-5)",
    "textAlign": "center",
    "color": "var(--ui-color-text-muted)",
    "fontSize": "var(--ui-font-size-sm)"
  },
  "[data-ui-theme-toggle]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "2px",
    "padding": "2px",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-surface-sunken)"
  },
  "[data-ui-theme-toggle-option]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-1)",
    "height": "var(--ui-control-height-sm)",
    "paddingInline": "var(--ui-space-3)",
    "border": "none",
    "borderRadius": "var(--ui-radius-sm)",
    "background": "transparent",
    "color": "var(--ui-color-text-muted)",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "cursor": "pointer",
    "transition": "background-color var(--ui-transition),\n    color var(--ui-transition)"
  },
  "[data-ui-theme-toggle-option]:hover": {
    "color": "var(--ui-color-text)"
  },
  "[data-ui-theme-toggle-option][data-state=\"checked\"]": {
    "background": "var(--ui-color-surface-raised)",
    "color": "var(--ui-color-text)",
    "boxShadow": "var(--ui-shadow-sm)"
  },
  "[data-ui-theme-toggle-option]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-workflow]": {
    "fontFamily": "var(--ui-font-family)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-workflow-steps]": {
    "display": "flex",
    "gap": "var(--ui-space-2)",
    "marginBottom": "var(--ui-space-5)"
  },
  "[data-ui-workflow-step]": {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "var(--ui-space-2)",
    "padding": "var(--ui-space-2) var(--ui-space-3)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-surface)",
    "color": "var(--ui-color-text-muted)",
    "fontFamily": "var(--ui-font-mono)",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "cursor": "pointer",
    "transition": "background-color var(--ui-transition),\n    border-color var(--ui-transition),\n    color var(--ui-transition)"
  },
  "[data-ui-workflow-step][data-complete]": {
    "color": "var(--ui-color-primary)",
    "borderStyle": "solid",
    "borderColor": "var(--ui-color-primary)"
  },
  "[data-ui-workflow-step][data-state=\"active\"]": {
    "background": "var(--ui-color-primary)",
    "borderStyle": "solid",
    "borderColor": "var(--ui-color-primary)",
    "color": "var(--ui-color-on-primary)"
  },
  "[data-ui-workflow-step]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-workflow-panel]": {
    "fontSize": "var(--ui-font-size-md)"
  },
  "[data-ui-workflow-next],\n[data-ui-workflow-previous]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "var(--ui-space-2)",
    "height": "var(--ui-control-height-md)",
    "marginTop": "var(--ui-space-4)",
    "marginRight": "var(--ui-space-2)",
    "paddingInline": "var(--ui-space-4)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-surface)",
    "color": "var(--ui-color-text)",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "cursor": "pointer",
    "transition": "background-color var(--ui-transition)"
  },
  "[data-ui-workflow-next]": {
    "background": "var(--ui-color-primary)",
    "borderColor": "var(--ui-color-primary)",
    "color": "var(--ui-color-on-primary)"
  },
  "[data-ui-workflow-next]:hover": {
    "background": "var(--ui-color-primary-hover)"
  },
  "[data-ui-workflow-previous]:hover": {
    "background": "var(--ui-color-muted)"
  },
  "[data-ui-workflow-next]:focus-visible,\n[data-ui-workflow-previous]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-workflow-next][data-disabled],\n[data-ui-workflow-previous][data-disabled]": {
    "opacity": 0.5,
    "pointerEvents": "none"
  },
  "[data-ui-aspect-ratio]": {
    "overflow": "hidden",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border)",
    "borderRadius": "var(--ui-radius-md)"
  },
  "[data-ui-machine]": {
    "fontFamily": "var(--ui-font-family)",
    "color": "var(--ui-color-text)"
  },
  "[data-ui-machine-state]": {
    "fontSize": "var(--ui-font-size-md)"
  },
  "[data-ui-machine-send]": {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "var(--ui-space-2)",
    "height": "var(--ui-control-height-md)",
    "marginRight": "var(--ui-space-2)",
    "paddingInline": "var(--ui-space-4)",
    "border": "var(--ui-border-width) var(--ui-border-style) var(--ui-color-border-strong)",
    "borderRadius": "var(--ui-radius-md)",
    "background": "var(--ui-color-primary)",
    "borderColor": "var(--ui-color-primary)",
    "color": "var(--ui-color-on-primary)",
    "fontFamily": "var(--ui-font-family)",
    "fontSize": "var(--ui-font-size-sm)",
    "fontWeight": "var(--ui-font-weight-medium)",
    "cursor": "pointer",
    "transition": "background-color var(--ui-transition)"
  },
  "[data-ui-machine-send]:hover": {
    "background": "var(--ui-color-primary-hover)"
  },
  "[data-ui-machine-send]:focus-visible": {
    "outline": "none",
    "boxShadow": "var(--ui-focus-ring)"
  },
  "[data-ui-machine-send][data-disabled]": {
    "opacity": 0.5,
    "pointerEvents": "none"
  }
};
