// Generates `src/styles/skin.generated.ts` from the canonical CSS so the
// Tailwind plugin can inject the SAME default skin + tokens that `skin.css` and
// `tokens.css` provide — without duplicating any of it. The CSS files stay the
// single source of truth; this just re-expresses them as CSS-in-JS objects that
// Tailwind's `addBase`/`addComponents` understand.
//
// Run via `npm run gen:skin` (also runs as part of `npm run build`).

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import { objectify } from "postcss-js";

const root = dirname(fileURLToPath(import.meta.url));
const stylesDir = resolve(root, "../src/styles");

const cssToObject = (file) =>
  objectify(postcss.parse(readFileSync(resolve(stylesDir, file), "utf8")));

const tokens = cssToObject("tokens.css");
const skin = cssToObject("skin.css");

const out = `// AUTO-GENERATED by scripts/gen-skin.mjs — DO NOT EDIT BY HAND.
// Source of truth: src/styles/tokens.css and src/styles/skin.css.
// Regenerate with \`npm run gen:skin\`.
/* eslint-disable */

/** A nestable CSS-in-JS style tree, as Tailwind's addBase/addComponents accept. */
export type StyleObject = { [selector: string]: string | number | StyleObject };

/** Token values as CSS-in-JS (e.g. \`{ ':root': { '--ui-color-primary': '#4f46e5' } }\`). */
export const tokensBase: StyleObject = ${JSON.stringify(tokens, null, 2)};

/** Default skin as CSS-in-JS, keyed by \`[data-ui-*]\` selectors and \`@keyframes\`. */
export const skinComponents: StyleObject = ${JSON.stringify(skin, null, 2)};
`;

writeFileSync(resolve(stylesDir, "skin.generated.ts"), out);
console.log("Generated src/styles/skin.generated.ts");
